# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'BHPostsCodeTest' do

    pod 'PKHUD', '~> 4.0'
    pod 'Gloss', '~> 1.2'
    pod 'Alamofire', '~> 4.3'
    pod 'SugarRecord/CoreData', '3.0'
    
end
